config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.urls import path

import mainapp
from mainapp.views import *

app_name = 'mainapp'

urlpatterns = [
    path('', main, name='main'),
    path('mainapp/learning', learning, name='learning'),
    path('ajax', ajax, name='ajax'),
    path('mainapp/game', game, name='game'),
    path('mainapp/wordlist', wordlist, name='wordlist'),
    path('mainapp/delete/<int:id>', mainapp.views.delete, name='delete'),
    path('detectme', detectme, name="detectme"),
    path('detectme2', detectme2, name="detectme2"),
]

mainapp/models.py
from django.db import models

class Word(models.Model):
    id = models.AutoField(primary_key=True)
    word = models.CharField(max_length=200, unique=True)
    images = models.ImageField(upload_to='static/images', null=True)
'''
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
'''

mainapp/views.py
import threading
import random
import cv2
import json
from django.http import StreamingHttpResponse
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators import gzip

# Create your views here.
from mainapp import yolo

from mainapp import models
from .models import Word
global pastFrame
def main(request):
    return render(request, 'index.html')

def learning(request):

    return render(request, 'learning.html')

def delete(request, id):
  w = Word.objects.get(id=id)
  w.delete()
  return render(request,'delete.html')

def ajax(request):
    words = yolo.labels
    context = {'words': words}
    response = json.dumps(context)
    wList = list(models.Word.objects.all().values_list('word', flat=True))

    print(wList)
    words = yolo.labels
    for idx, val in enumerate(yolo.images):
        if words[idx] in wList:
            continue
        print(r"static"+"\\images\\" + words[idx] + ".png")
        cv2.imwrite(r"static"+"\\images\\" + words[idx] + ".png", val)
        physics = models.Word(word=yolo.labels[idx], images=r"static"+"\\images\\" + words[idx] + ".png")
        physics.save()

    #print(response)
    return HttpResponse(response)
    # return HttpResponse(json.dumps(data), content_type='application/json')

def game(request):
    wordList = models.Word.objects.all()
    wordList2 = Word.objects.order_by('?')[:5]
    outerStr = "["
    wList = [" ", " ", " "]
    nList = [" ", " ", " "]
    print(len(wordList))
    print(len(wordList2))
    for item in wordList2:
        tmpN = random.randint(0,10)
        wList[0] = wordList[random.randint(0, len(wordList)-1)].word
        wList[1] = wordList[random.randint(0, len(wordList)-1)].word
        wList[2] = item.word

        nList[(tmpN + 0) % 3] = wList[0]
        nList[(tmpN + 1) % 3] = wList[1]
        nList[(tmpN + 2) % 3] = wList[2]

        str = "{\n"
        str += "\"question\": \"" + item.word + "\",\n"
        str += "\"a\": \"" + nList[0] + "\",\n"
        str += "\"b\": \"" + nList[1] + "\",\n"
        str += "\"c\": \"" + nList[2] + "\",\n"
        str += "\"correct\": \""+chr(97+((tmpN + 2) % 3)) +"\"\n"
        str += "},\n"
        print(str)

        outerStr += str

    outerStr = outerStr[:-2]
    outerStr += "]"
    print("outer")
    print(outerStr)
    jTmp = json.loads(outerStr)
    print(jTmp)
    #words = jTmp
    context = {"words": jTmp}
    #print(context)

    return render(request, 'game.html', context)

def portfolio(request):
    return render(request, 'portfolio.html')

def portfolio_details(request):
    return render(request, 'portfolio-details.html')

def wordlist(request):
    context = {
        "words": models.Word.objects.all()
    }
    return render(request, 'wordlist.html', context)

def services(request):
    return render(request, 'services.html')

class VideoCamera(object):
    def __init__(self):
        self.video = cv2.VideoCapture(0, cv2.CAP_DSHOW)
        #self.video = set(cv2.CAP_PROP_FPS, 10)
        (self.grabbed, self.frame) = self.video.read()
        threading.Thread(target=self.update, args=()).start()

    def __del__(self):
        self.video.release()

    def get_frame(self):
        image = self.frame
        image = yolo.detection(image)
        _, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()

    def get_frame2(self):
        image = self.frame
        image = yolo.detection2(image)
        _, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()

    def update(self):
        while True:
            (self.grabbed, self.frame) = self.video.read()

def gen(camera):
    while True:
        frame = camera.get_frame()

        yield(b'--frame\r\n'
              b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

def gen2(camera):
    global pastFrame
    flag = True
    while True:
        if flag:
            frame = camera.get_frame()
            pastFrame = frame
            flag = False
        else:
            frame = pastFrame

        yield(b'--frame\r\n'
              b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@gzip.gzip_page
def detectme(request):
    try:
        cam = VideoCamera()
        return StreamingHttpResponse(gen(cam), content_type="multipart/x-mixed-replace;boundary=frame")
    except:  # This is bad! replace it with proper handling
        print("에러입니다...")
        pass
def detectme2(request):
    try:
        cam = VideoCamera()
        #return gen2(cam)
        return StreamingHttpResponse(gen2(cam), content_type="multipart/x-mixed-replace;boundary=frame")
    except:  # This is bad! replace it with proper handling
        print("에러입니다...")
        pass

mainapp/templates/about.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}
{% include "header.html" %}

<body>
  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>About</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">
          <div class="col-lg-4">
            <img src="/static/img/about.jpg" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content">
            <h3>Illustrator &amp; UI/UX Designer</h3>
            <p class="fst-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-rounded-right"></i> <strong>Birthday:</strong> 1 May 1995</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>Website:</strong> www.example.com</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>Phone:</strong> +123 456 7890</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>City:</strong> City : New York, USA</li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-rounded-right"></i> <strong>Age:</strong> 30</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>Degree:</strong> Master</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>PhEmailone:</strong> email@example.com</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>Freelance:</strong> Available</li>
                </ul>
              </div>
            </div>
            <p>
              Officiis eligendi itaque labore et dolorum mollitia officiis optio vero. Quisquam sunt adipisci omnis et ut. Nulla accusantium dolor incidunt officia tempore. Et eius omnis.
              Cupiditate ut dicta maxime officiis quidem quia. Sed et consectetur qui quia repellendus itaque neque. Aliquid amet quidem ut quaerat cupiditate. Ab et eum qui repellendus omnis culpa magni laudantium dolores.
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Skills Section ======= -->
    <section id="skills" class="skills">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Skills</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row skills-content">

          <div class="col-lg-6">

            <div class="progress">
              <span class="skill">HTML <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">CSS <i class="val">90%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">JavaScript <i class="val">75%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

          </div>

          <div class="col-lg-6">

            <div class="progress">
              <span class="skill">PHP <i class="val">80%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">WordPress/CMS <i class="val">90%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">Photoshop <i class="val">55%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

          </div>

        </div>

      </div>
    </section><!-- End Skills Section -->

    <!-- ======= Facts Section ======= -->
    <section id="facts" class="facts">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Facts</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row counters">

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
            <p>Clients</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter"></span>
            <p>Projects</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1" class="purecounter"></span>
            <p>Hours Of Support</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
            <p>Hard Workers</p>
          </div>

        </div>

      </div>
    </section><!-- End Facts Section -->

    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Testimonials</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src="/static/img/testimonials/testimonials-1.jpg" class="testimonial-img" alt="">
                <h3>Saul Goodman</h3>
                <h4>Ceo &amp; Founder</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src="/static/img/testimonials/testimonials-2.jpg" class="testimonial-img" alt="">
                <h3>Sara Wilsson</h3>
                <h4>Designer</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src="/static/img/testimonials/testimonials-3.jpg" class="testimonial-img" alt="">
                <h3>Jena Karlis</h3>
                <h4>Store Owner</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src="/static/img/testimonials/testimonials-4.jpg" class="testimonial-img" alt="">
                <h3>Matt Brandon</h3>
                <h4>Freelancer</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src="/static/img/testimonials/testimonials-5.jpg" class="testimonial-img" alt="">
                <h3>John Larson</h3>
                <h4>Entrepreneur</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->

  </main><!-- End #main -->

 
  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="/static/vendor/purecounter/purecounter.js"></script>
  <script src="/static/vendor/aos/aos.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="/static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/js/main.js"></script>

</body>
{% include "footer.html" %}
</html>

mainapp/templates/delete.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}

{% include "header.html" %}
<body>
    <main id="main">
        <style>
            .bi-house-fill {
                border-radius: 15px;
            background-color: #fff;
            line-height: 10px;
              margin-right: 5px;
              margin-left: 20px;
              margin-top: 10px;
              margin-bottom: 20px;
            padding: 15px;
            border: #ff7a85;
              border-style: solid;
            }
        </style>

    <a href="../../" class="bi-house-fill" style="font-weight: bold; font-size: 20px; font-family: Raleway"> Go home</a>
    <h1 style="text-align: center; margin-bottom: 30px; font-family: Roboto; font-size: 70px; font-weight: bolder;">the word is deleted!</h1>
    </main>
</body>
</html>
© 2022

mainapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}
{% include "header.html" %}
<body>


  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container d-flex flex-column align-items-center" data-aos="zoom-in" data-aos-delay="100">
      <h1 style="font-family: Roboto; font-size: 70px; font-weight: bolder; margin-bottom: 30px">Daily word</h1>
      <h2 style="font-weight: bold; font-family: Roboto;">Select the modes!</h2>
      <a href="mainapp/learning" class="btn-about">Learning Mode</a>
      <a href="mainapp/game" class="btn-about">Game Mode</a>
      <a href="mainapp/wordlist" class="btn-about">Word List</a>
    </div>
  </section><!-- End Hero -->

  {% include "footer.html" %}
  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="static/vendor/purecounter/purecounter.js"></script>
  <script src="static/vendor/aos/aos.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="static/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="static/js/main.js"></script>

</body>

</html>

mainapp/templates/learning.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% include "header.html" %}

<body>
  <main id="main">

    <style>
      .show-btn{
        border-radius: 20px;
            background-color: #ffc0cb;
            background-image: linear-gradient(315deg, #ffc0cb 0%, #ff7a85 74%);
            line-height: 10px;
              margin-top: 10px;
              margin-right: 5px;
              margin-left: 5px;
              margin-bottom: 10px;
            padding: 15px;
            border: none;
            }
            .show-btn span {
                position: relative;
                display: block;
                width: 100%;
                height: 100%;
            }
          .show-btn:before,
            .show-btn:after {
            position: absolute;
            content: "";
            right: 0;
            bottom: 0;
            background: #ffd4df;
            box-shadow:  1px 1px 2px 0 rgba(234,76,137,1),
              -1px -1px 2px 0 rgba(116, 125, 136, .2),
                inset -1px -1px 2px 0 rgba(255,255,255,.5),
                inset 1px 1px 2px 0 rgba(116, 125, 136, .3);
            transition: all 0.3s ease;
            }

          .show-btn:before{
            height: 0%;
            width: 10px;
            }
            .show-btn:after {
            width: 0%;
            height: 2px;
            }
            .show-btn:hover{
            background: #ffd4df;
            }

            .bi-arrow-left{
              border-radius: 15px;
            background-color: #fff;
            line-height: 10px;
              margin-right: 5px;
              margin-left: 20px;
              margin-top: 10px;
              margin-bottom: 20px;
            padding: 15px;
            border: #ff7a85;
              border-style: solid;
            }

            .bi-play-circle-fill{
        border-radius: 30px;
            background-color: #ffc0cb;
            background-image: linear-gradient(315deg, #ffe3ee 0%, #ff848f 74%);
            line-height: 10px;
              margin-right: 5px;
              margin-left: 5px;
              margin-top: 10px;
              margin-bottom: 20px;
            padding: 15px;
            border: none;
            }


            input {display: none;}
            label {
              display: inline-block;
              width: 80px;
              border-radius: 70px;
              height: 34px;
              cursor: pointer;
              position: relative;
              background-color: #ccc;
            }
            label::before {
              content: '';
              display: block;
              width: 26px;
              height: 26px;
              left: 4px;
              bottom: 4px;
              position: absolute;
              background-color: #fff;
              transition: all.4s ease;
            }

            input:checked + label {background-color: #ffc0cb;}
            input:checked + label:before{
              transform: translateX(40px);
            }
            label.rounded-2 {border-radius: 30px}
            label.rounded-2::before {border-radius: 100%}
    </style>

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="about">
      <a href="../" class="bi-arrow-left" style="font-weight: bold; font-family: Raleway"> back</a>
      </div>

      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2 style="font-family: Roboto; font-size: 40px;">Learning Mode</h2>
          <p></p>
        </div>

        <div class="row">
          <div class="col-lg-4">
            <img id = "camimg" src="http://127.0.0.1:8000/detectme" class="img-fluid" alt="">
            <!--<button id ="camtoggle" class="bi-camera-fill" onclick="toggleImg()"></button> -->
            <input type="checkbox" id="switch_btn" class="rounded-2" onclick="toggleImg()">
            <label id = "camtoggle" for="switch_btn" class="rounded-2" onclick=""></label>

            <script type="text/javascript">
              let flag = false;
              function toggleImg() {
                document.getElementById("camimg").src = flag
                  ? "http://127.0.0.1:8000/detectme"
                  : "http://127.0.0.1:8000/detectme2";
                flag = !flag;
              }
            </script>

              </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content">
            <h3>Word List</h3>

              <div id = "update1" class="learning-update-content">

             <script>
                      function speak(text) {
                          if (typeof SpeechSynthesisUtterance === "undefined" || typeof window.speechSynthesis === "undefined") {
                              alert("이 브라우저는 음성 합성을 지원하지 않습니다.")
                              return
                          }

                          window.speechSynthesis.cancel() // 현재 읽고있다면 초기화

                          const speechMsg = new SpeechSynthesisUtterance()
                          speechMsg.rate = 1 // 속도: 0.1 ~ 10
                          speechMsg.pitch = 1 // 음높이: 0 ~ 2
                          speechMsg.lang = "es"
                          speechMsg.text = text

                          // SpeechSynthesisUtterance에 저장된 내용을 바탕으로 음성합성 실행
                          window.speechSynthesis.speak(speechMsg)
                      }



                   </script>
              </div>
              <script>
                  $('#camtoggle').click(function() {
                      $.ajax({
                          url:'{% url 'mainapp:ajax' %}',
                          dataType: 'json',
                          success: function(data){
                              alert('good');
                              var str= '';
                              for (var words in data.words){
                                  str += '<p class="fst-italic" style="font-size:30px; font-weight: 900;">'+data.words[words]+'</p>'; // key값 출력시 name
                                  str += '<button onclick="speak(\''+data.words[words]+'\')" class="bi-play-circle-fill"></button>';
                              }
                              $('#update1').html('<ul>'+str+'</ul>')
                          },
                          error: function(request, status, error){
                              alert('bad');
                              alert(error);
                              $('#update1').html('AJAX 통신에 실패했습니다.')
                          }
                      })
                  })
              </script>




            </div>

          </div>
        </div>

      </div>
    </section><!-- End About Section -->



          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->


  </main><!-- End #main -->

 
  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="/static/vendor/purecounter/purecounter.js"></script>
  <script src="/static/vendor/aos/aos.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="/static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/js/main.js"></script>

</body>
{% include "footer.html" %}
</html>

mainapp/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <h4>Hello</h4>
    </body>
</html>

templates/footer.html
<footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Kelly</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        
        
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
</footer><!-- End  Footer -->

templates/header.html
<header id="header" class="fixed-top">
    <div class="container-fluid d-flex justify-content-between align-items-center">


      <!-- <h1 class="logo me-auto me-lg-0"><a href="">Daily Word</a></h1> -->
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="/static/img/logo.png" alt="" class="img-fluid"></a>-->


      <!-- <div class="header-social-links">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
      </div> -->

    </div>

  </header><!-- End Header -->